trigger:
- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'Kayal'
    cliInstallationRepo: 'jfrog-cli'
    installCustomVersion: true
    cliVersion: '1.46.0'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: 35.199.116.14:80/test-docker/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'Kayal'
    buildName: 'testBuild'
    buildNumber: '1'
    allowFailBuild: false
